"""
Core Event and Data Structures for AlphaForge.
Immutable data containers for market data, trade setups, orders, and execution records.
"""
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional, Dict, Any, List
from src.core.enums import OrderSide, OrderType, OrderStatus, LossCategory


@dataclass(frozen=True)
class BarEvent:
    """
    Immutable bar representing a single period of price action.
    Strategies consume BarEvents and must never mutate them.
    """
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float
    symbol: str
    timeframe: str = "5m"
    session_id: Optional[str] = None
    is_rth: bool = True
    atr_14: Optional[float] = None

    @property
    def range(self) -> float:
        return self.high - self.low

    @property
    def body(self) -> float:
        return abs(self.close - self.open)

    @property
    def is_bullish(self) -> bool:
        return self.close > self.open

    @property
    def is_bearish(self) -> bool:
        return self.close < self.open


@dataclass
class TradeSetup:
    """
    Pure abstract trade signal generated by an alpha strategy.
    Strategy is completely blind to account balance, current positions, and execution details.
    """
    direction: OrderSide
    order_type: OrderType
    stop_loss: float               # Absolute price
    take_profit: float             # Absolute price
    limit_price: Optional[float] = None
    ttl_bars: int = 12             # Cancellation horizon for pending limit orders
    time_stop_bars: Optional[int] = None  # Max holding duration before inertia/time exit
    protect_at_1r: bool = False    # Tighten SL to BE once MFE reaches >= +0.85R
    tag: str = "default"           # Sub-setup identifier for forensic attribution
    metadata: Dict[str, Any] = field(default_factory=dict)

    def validate(self, current_price: float) -> bool:
        """Validate logical geometry of stop loss and take profit."""
        if self.direction == OrderSide.LONG:
            return self.stop_loss < current_price and self.take_profit > current_price
        else:
            return self.stop_loss > current_price and self.take_profit < current_price


@dataclass
class OrderEvent:
    """Order submitted to the execution simulator."""
    order_id: str
    timestamp: datetime
    symbol: str
    side: OrderSide
    order_type: OrderType
    quantity: int
    stop_loss: float
    take_profit: float
    limit_price: Optional[float] = None
    ttl_bars: int = 12
    time_stop_bars: Optional[int] = None
    protect_at_1r: bool = False
    bars_active: int = 0
    tag: str = "default"
    metadata: Dict[str, Any] = field(default_factory=dict)
    status: OrderStatus = OrderStatus.PENDING


@dataclass
class FillEvent:
    """Execution fill returned by the execution simulator."""
    fill_id: str
    order_id: str
    timestamp: datetime
    symbol: str
    side: OrderSide
    price: float
    quantity: int
    commission: float
    slippage_ticks: float
    slippage_cost: float


@dataclass
class TradeRecord:
    """
    Full forensic post-mortem trade record for diagnostics and analytics.
    Tracks intra-trade excursion (MFE/MAE), timing, friction, and loss taxonomy.
    """
    trade_id: str
    symbol: str
    strategy_name: str
    tag: str
    side: OrderSide
    contracts: int
    
    # Timestamps & Prices
    entry_time: datetime
    entry_price: float
    exit_time: datetime
    exit_price: float
    exit_reason: str              # 'STOP_LOSS', 'TAKE_PROFIT', 'SESSION_CLOSE', 'BREACH_LIQUIDATION'
    
    # Target Geometry
    initial_sl: float
    initial_tp: float
    risk_r_price: float           # |Entry - SL|
    
    # Excursion Tracking (in points & in R units)
    mfe_price: float              # Max favorable price reached during trade
    mae_price: float              # Max adverse price reached during trade
    mfe_r: float                  # MFE normalized by initial risk R
    mae_r: float                  # MAE normalized by initial risk R
    time_to_peak_mfe: int         # Number of bars elapsed until MFE was attained
    bars_held: int                # Total bars held
    
    # PnL & Friction
    gross_pnl: float
    net_pnl: float
    commissions: float
    slippage_paid: float
    
    # R-Multiple realized
    r_multiple: float
    
    # Forensic metrics
    excursion_efficiency: float   # Realized / MFE
    loss_category: Optional[LossCategory] = None
    
    # Regime tags
    entry_hour_est: int = 9
    day_of_week: str = "Monday"
    atr_quintile: int = 3
    is_rth: bool = True
